 user:
  deleted: true
  wait: 0
  accept: 1
  begin: 2
  close: 3
  number : 1
  panigate_size: 6
  email:
    default: "nguyenduyson60@example.com"
    layout: "mailer"
    max_length: 255
 min_number: 1
 min_quantity: 0
